"""drop users.phone (data minimization)

Revision ID: 070cc39f9476
Revises: 5507d9f4a343
Create Date: 2026-07-21 17:50:47.490441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070cc39f9476'
down_revision: Union[str, Sequence[str], None] = '5507d9f4a343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
