"""helpful votes

Revision ID: 095be758ae68
Revises: 764ad0f7b8aa
Create Date: 2026-07-24 00:23:46.549396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095be758ae68'
down_revision: Union[str, Sequence[str], None] = '764ad0f7b8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpful_votes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(review_id IS NULL) <> (complaint_id IS NULL)', name=op.f('ck_helpful_votes_exactly_one_parent')),
    sa.ForeignKeyConstraint(['complaint_id'], ['vacancy_complaints.id'], name=op.f('fk_helpful_votes_complaint_id_vacancy_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_helpful_votes_review_id_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_helpful_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_helpful_votes')),
    sa.UniqueConstraint('user_id', 'review_id', 'complaint_id', name=op.f('uq_helpful_votes_user_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_helpful_votes_complaint_id'), 'helpful_votes', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_helpful_votes_review_id'), 'helpful_votes', ['review_id'], unique=False)
    op.create_index(op.f('ix_helpful_votes_user_id'), 'helpful_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_helpful_votes_user_id'), table_name='helpful_votes')
    op.drop_index(op.f('ix_helpful_votes_review_id'), table_name='helpful_votes')
    op.drop_index(op.f('ix_helpful_votes_complaint_id'), table_name='helpful_votes')
    op.drop_table('helpful_votes')
    # ### end Alembic commands ###
