"""post reports

Revision ID: 2e86170e63e1
Revises: 6f97ec543056
Create Date: 2026-07-24 00:57:52.961248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e86170e63e1'
down_revision: Union[str, Sequence[str], None] = '6f97ec543056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('is_company_claim', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_claim', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('false_facts', 'defamation', 'pii_exposed', 'fake_evidence', 'insult', 'spam', 'other')", name=op.f('ck_post_reports_reason_valid')),
    sa.CheckConstraint("status IN ('open', 'resolved_hidden', 'resolved_kept')", name=op.f('ck_post_reports_status_valid')),
    sa.CheckConstraint('num_nonnulls(review_id, complaint_id, comment_id) = 1', name=op.f('ck_post_reports_exactly_one_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_post_reports_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['vacancy_complaints.id'], name=op.f('fk_post_reports_complaint_id_vacancy_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_post_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_post_reports_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_post_reports_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_reports'))
    )
    op.create_index(op.f('ix_post_reports_comment_id'), 'post_reports', ['comment_id'], unique=False)
    op.create_index(op.f('ix_post_reports_complaint_id'), 'post_reports', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_post_reports_reporter_id'), 'post_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_post_reports_review_id'), 'post_reports', ['review_id'], unique=False)
    op.add_column('evidence_files', sa.Column('report_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_evidence_files_report_id'), 'evidence_files', ['report_id'], unique=False)
    op.create_foreign_key(op.f('fk_evidence_files_report_id_post_reports'), 'evidence_files', 'post_reports', ['report_id'], ['id'], ondelete='CASCADE')
    # Қолмен: үш CHECK-констрейнт жаңарады (autogenerate байқамайды)
    op.drop_constraint('exactly_one_parent', 'evidence_files', type_='check')
    op.create_check_constraint('exactly_one_parent', 'evidence_files', 'num_nonnulls(review_id, complaint_id, report_id) = 1')
    op.drop_constraint('purpose_valid', 'evidence_files', type_='check')
    op.create_check_constraint('purpose_valid', 'evidence_files', "purpose IN ('public_evidence', 'verification', 'report')")
    op.drop_constraint('target_type_valid', 'moderation_actions', type_='check')
    op.create_check_constraint('target_type_valid', 'moderation_actions', "target_type IN ('review', 'complaint', 'evidence', 'response', 'company', 'user', 'badge', 'representative', 'comment', 'report')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('target_type_valid', 'moderation_actions', type_='check')
    op.create_check_constraint('target_type_valid', 'moderation_actions', "target_type IN ('review', 'complaint', 'evidence', 'response', 'company', 'user', 'badge', 'representative', 'comment')")
    op.drop_constraint('purpose_valid', 'evidence_files', type_='check')
    op.create_check_constraint('purpose_valid', 'evidence_files', "purpose IN ('public_evidence', 'verification')")
    op.drop_constraint('exactly_one_parent', 'evidence_files', type_='check')
    op.create_check_constraint('exactly_one_parent', 'evidence_files', '(review_id IS NULL) <> (complaint_id IS NULL)')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_evidence_files_report_id_post_reports'), 'evidence_files', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_files_report_id'), table_name='evidence_files')
    op.drop_column('evidence_files', 'report_id')
    op.drop_index(op.f('ix_post_reports_review_id'), table_name='post_reports')
    op.drop_index(op.f('ix_post_reports_reporter_id'), table_name='post_reports')
    op.drop_index(op.f('ix_post_reports_complaint_id'), table_name='post_reports')
    op.drop_index(op.f('ix_post_reports_comment_id'), table_name='post_reports')
    op.drop_table('post_reports')
    # ### end Alembic commands ###
