"""initial schema

Revision ID: 5507d9f4a343
Revises:
Create Date: 2026-07-21 16:30:18.695153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5507d9f4a343'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('labor_code_article', sa.Text(), nullable=True),
    sa.Column('body_kk', sa.Text(), nullable=False),
    sa.Column('body_ru', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved')", name=op.f('ck_daily_tips_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_tips'))
    )
    op.create_index(op.f('ix_daily_tips_published_on'), 'daily_tips', ['published_on'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('pseudonym', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('trust_level', sa.Text(), server_default='user', nullable=False),
    sa.Column('karma', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locale', sa.Text(), server_default='kk', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('worker', 'company')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint("trust_level IN ('user', 'trusted', 'moderator', 'admin')", name=op.f('ck_users_trust_level_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('pseudonym', name=op.f('uq_users_pseudonym'))
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('oked', sa.Text(), nullable=True),
    sa.Column('two_gis_url', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_reason', sa.Text(), nullable=True),
    sa.Column('hidden_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('registry_import', 'user_created')", name=op.f('ck_companies_source_valid')),
    sa.CheckConstraint('char_length(bin) = 12', name=op.f('ck_companies_bin_length')),
    sa.ForeignKeyConstraint(['hidden_by_id'], ['users.id'], name=op.f('fk_companies_hidden_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('bin', name=op.f('uq_companies_bin'))
    )
    op.create_table('karma_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_karma_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_karma_events'))
    )
    op.create_index(op.f('ix_karma_events_user_id'), 'karma_events', ['user_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('second_approver_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('hide', 'unhide', 'approve', 'reject', 'mask_pii', 'verify_review', 'award_badge', 'revoke_badge', 'ban_user', 'other')", name=op.f('ck_moderation_actions_action_valid')),
    sa.CheckConstraint("target_type IN ('review', 'complaint', 'evidence', 'response', 'company', 'user', 'badge')", name=op.f('ck_moderation_actions_target_type_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_moderation_actions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['second_approver_id'], ['users.id'], name=op.f('fk_moderation_actions_second_approver_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_actions'))
    )
    op.create_index(op.f('ix_moderation_actions_actor_id'), 'moderation_actions', ['actor_id'], unique=False)
    op.create_index(op.f('ix_moderation_actions_target_id'), 'moderation_actions', ['target_id'], unique=False)
    op.create_table('appeals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('appellant_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'upheld', 'overturned')", name=op.f('ck_appeals_status_valid')),
    sa.ForeignKeyConstraint(['action_id'], ['moderation_actions.id'], name=op.f('fk_appeals_action_id_moderation_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['appellant_id'], ['users.id'], name=op.f('fk_appeals_appellant_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_appeals_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appeals'))
    )
    op.create_index(op.f('ix_appeals_action_id'), 'appeals', ['action_id'], unique=False)
    op.create_table('company_badges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('badge', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("badge IN ('salary_not_confirmed', 'repeated_language_discrimination', 'officially_confirmed_violation')", name=op.f('ck_company_badges_badge_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_badges_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_badges'))
    )
    op.create_index(op.f('ix_company_badges_company_id'), 'company_badges', ['company_id'], unique=False)
    op.create_table('company_representatives',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('proof_method', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("proof_method IS NULL OR proof_method IN ('domain_email', 'official_letter', 'other')", name=op.f('ck_company_representatives_proof_method_valid')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_company_representatives_status_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_representatives_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_company_representatives_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_company_representatives_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_representatives')),
    sa.UniqueConstraint('company_id', 'user_id', name=op.f('uq_company_representatives_company_id'))
    )
    op.create_index(op.f('ix_company_representatives_company_id'), 'company_representatives', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_representatives_user_id'), 'company_representatives', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.SmallInteger(), nullable=False),
    sa.Column('score_salary_timeliness', sa.SmallInteger(), nullable=True),
    sa.Column('score_pension', sa.SmallInteger(), nullable=True),
    sa.Column('score_overtime', sa.SmallInteger(), nullable=True),
    sa.Column('score_contract', sa.SmallInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('employment_start', sa.Date(), nullable=True),
    sa.Column('employment_end', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.Text(), server_default='unverified', nullable=False),
    sa.Column('moderation_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_reason', sa.Text(), nullable=True),
    sa.Column('hidden_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('pending', 'published', 'hidden')", name=op.f('ck_reviews_moderation_status_valid')),
    sa.CheckConstraint("verification_status IN ('unverified', 'pending', 'verified', 'rejected')", name=op.f('ck_reviews_verification_status_valid')),
    sa.CheckConstraint('overall_score BETWEEN 1 AND 10', name=op.f('ck_reviews_overall_score_range')),
    sa.CheckConstraint('score_contract IS NULL OR score_contract BETWEEN 1 AND 10', name=op.f('ck_reviews_score_contract_range')),
    sa.CheckConstraint('score_overtime IS NULL OR score_overtime BETWEEN 1 AND 10', name=op.f('ck_reviews_score_overtime_range')),
    sa.CheckConstraint('score_pension IS NULL OR score_pension BETWEEN 1 AND 10', name=op.f('ck_reviews_score_pension_range')),
    sa.CheckConstraint('score_salary_timeliness IS NULL OR score_salary_timeliness BETWEEN 1 AND 10', name=op.f('ck_reviews_score_salary_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_reviews_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hidden_by_id'], ['users.id'], name=op.f('fk_reviews_hidden_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('company_id', 'author_id', name=op.f('uq_reviews_company_id'))
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_company_id'), 'reviews', ['company_id'], unique=False)
    op.create_table('vacancy_complaints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('advertised_salary', sa.Integer(), nullable=True),
    sa.Column('actual_salary', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_reason', sa.Text(), nullable=True),
    sa.Column('hidden_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('salary_fraud', 'fake_vacancy', 'paid_training', 'unethical_questions', 'rudeness', 'ghost_vacancy', 'unpaid_test_task', 'discrimination')", name=op.f('ck_vacancy_complaints_category_valid')),
    sa.CheckConstraint("moderation_status IN ('pending', 'published', 'hidden')", name=op.f('ck_vacancy_complaints_moderation_status_valid')),
    sa.CheckConstraint("source_type IN ('hh', 'olx', 'instagram', 'threads', 'telegram', 'whatsapp', 'other')", name=op.f('ck_vacancy_complaints_source_type_valid')),
    sa.CheckConstraint("stage IN ('announcement', 'call', 'interview', 'offer')", name=op.f('ck_vacancy_complaints_stage_valid')),
    sa.CheckConstraint('actual_salary IS NULL OR actual_salary >= 0', name=op.f('ck_vacancy_complaints_actual_salary_positive')),
    sa.CheckConstraint('advertised_salary IS NULL OR advertised_salary >= 0', name=op.f('ck_vacancy_complaints_advertised_salary_positive')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_vacancy_complaints_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_vacancy_complaints_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hidden_by_id'], ['users.id'], name=op.f('fk_vacancy_complaints_hidden_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy_complaints'))
    )
    op.create_index(op.f('ix_vacancy_complaints_author_id'), 'vacancy_complaints', ['author_id'], unique=False)
    op.create_index(op.f('ix_vacancy_complaints_company_id'), 'vacancy_complaints', ['company_id'], unique=False)
    op.create_table('company_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('pending', 'published', 'hidden')", name=op.f('ck_company_responses_moderation_status_valid')),
    sa.CheckConstraint('(review_id IS NULL) <> (complaint_id IS NULL)', name=op.f('ck_company_responses_exactly_one_parent')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_company_responses_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_responses_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['vacancy_complaints.id'], name=op.f('fk_company_responses_complaint_id_vacancy_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_company_responses_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_responses'))
    )
    op.create_index(op.f('ix_company_responses_company_id'), 'company_responses', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_responses_complaint_id'), 'company_responses', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_company_responses_review_id'), 'company_responses', ['review_id'], unique=False)
    op.create_table('discrimination_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('form', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("form IN ('vacancy_text', 'interview', 'at_work')", name=op.f('ck_discrimination_details_form_valid')),
    sa.CheckConstraint("kind IN ('language', 'age', 'gender', 'ethnicity', 'other')", name=op.f('ck_discrimination_details_kind_valid')),
    sa.CheckConstraint('(review_id IS NULL) <> (complaint_id IS NULL)', name=op.f('ck_discrimination_details_exactly_one_parent')),
    sa.ForeignKeyConstraint(['complaint_id'], ['vacancy_complaints.id'], name=op.f('fk_discrimination_details_complaint_id_vacancy_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_discrimination_details_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discrimination_details'))
    )
    op.create_index(op.f('ix_discrimination_details_complaint_id'), 'discrimination_details', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_discrimination_details_review_id'), 'discrimination_details', ['review_id'], unique=False)
    op.create_table('evidence_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.Text(), server_default='public_evidence', nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('pii_masked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending_moderation', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('public_evidence', 'verification')", name=op.f('ck_evidence_files_purpose_valid')),
    sa.CheckConstraint("status IN ('pending_moderation', 'visible', 'hidden', 'deleted')", name=op.f('ck_evidence_files_status_valid')),
    sa.CheckConstraint('(review_id IS NULL) <> (complaint_id IS NULL)', name=op.f('ck_evidence_files_exactly_one_parent')),
    sa.ForeignKeyConstraint(['complaint_id'], ['vacancy_complaints.id'], name=op.f('fk_evidence_files_complaint_id_vacancy_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_evidence_files_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_files'))
    )
    op.create_index(op.f('ix_evidence_files_complaint_id'), 'evidence_files', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_review_id'), 'evidence_files', ['review_id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name=op.f('ck_verification_records_decision_valid')),
    sa.CheckConstraint("method IN ('employment_contract', 'bank_statement', 'other')", name=op.f('ck_verification_records_method_valid')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_verification_records_review_id_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_verification_records_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_records')),
    sa.UniqueConstraint('review_id', name=op.f('uq_verification_records_review_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_evidence_files_review_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_complaint_id'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_discrimination_details_review_id'), table_name='discrimination_details')
    op.drop_index(op.f('ix_discrimination_details_complaint_id'), table_name='discrimination_details')
    op.drop_table('discrimination_details')
    op.drop_index(op.f('ix_company_responses_review_id'), table_name='company_responses')
    op.drop_index(op.f('ix_company_responses_complaint_id'), table_name='company_responses')
    op.drop_index(op.f('ix_company_responses_company_id'), table_name='company_responses')
    op.drop_table('company_responses')
    op.drop_index(op.f('ix_vacancy_complaints_company_id'), table_name='vacancy_complaints')
    op.drop_index(op.f('ix_vacancy_complaints_author_id'), table_name='vacancy_complaints')
    op.drop_table('vacancy_complaints')
    op.drop_index(op.f('ix_reviews_company_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_company_representatives_user_id'), table_name='company_representatives')
    op.drop_index(op.f('ix_company_representatives_company_id'), table_name='company_representatives')
    op.drop_table('company_representatives')
    op.drop_index(op.f('ix_company_badges_company_id'), table_name='company_badges')
    op.drop_table('company_badges')
    op.drop_index(op.f('ix_appeals_action_id'), table_name='appeals')
    op.drop_table('appeals')
    op.drop_index(op.f('ix_moderation_actions_target_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_actor_id'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_karma_events_user_id'), table_name='karma_events')
    op.drop_table('karma_events')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_index(op.f('ix_daily_tips_published_on'), table_name='daily_tips')
    op.drop_table('daily_tips')
    # ### end Alembic commands ###
