"""offer difficulty pros cons

Revision ID: 6f97ec543056
Revises: 095be758ae68
Create Date: 2026-07-24 00:29:35.950226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f97ec543056'
down_revision: Union[str, Sequence[str], None] = '095be758ae68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pros', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('cons', sa.Text(), nullable=True))
    op.add_column('vacancy_complaints', sa.Column('got_offer', sa.Boolean(), nullable=True))
    op.add_column('vacancy_complaints', sa.Column('difficulty', sa.SmallInteger(), nullable=True))
    op.create_check_constraint('difficulty_range', 'vacancy_complaints', 'difficulty IS NULL OR difficulty BETWEEN 1 AND 5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('difficulty_range', 'vacancy_complaints', type_='check')
    op.drop_column('vacancy_complaints', 'difficulty')
    op.drop_column('vacancy_complaints', 'got_offer')
    op.drop_column('reviews', 'cons')
    op.drop_column('reviews', 'pros')
    # ### end Alembic commands ###
