"""comments table

Revision ID: 764ad0f7b8aa
Revises: 2dc9e481533f
Create Date: 2026-07-23 19:36:41.624547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764ad0f7b8aa'
down_revision: Union[str, Sequence[str], None] = '2dc9e481533f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('complaint_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('moderation_status', sa.Text(), server_default='published', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_reason', sa.Text(), nullable=True),
    sa.Column('hidden_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('pending', 'published', 'hidden')", name=op.f('ck_comments_moderation_status_valid')),
    sa.CheckConstraint('(review_id IS NULL) <> (complaint_id IS NULL)', name=op.f('ck_comments_exactly_one_parent')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['vacancy_complaints.id'], name=op.f('fk_comments_complaint_id_vacancy_complaints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hidden_by_id'], ['users.id'], name=op.f('fk_comments_hidden_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_comments_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_complaint_id'), 'comments', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_comments_review_id'), 'comments', ['review_id'], unique=False)
    # Аудит-лог CHECK-тізіміне 'comment' нысаны қосылады (autogenerate көрмейді)
    op.drop_constraint('target_type_valid', 'moderation_actions', type_='check')
    op.create_check_constraint(
        'target_type_valid',
        'moderation_actions',
        "target_type IN ('review', 'complaint', 'evidence', 'response', "
        "'company', 'user', 'badge', 'representative', 'comment')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('target_type_valid', 'moderation_actions', type_='check')
    op.create_check_constraint(
        'target_type_valid',
        'moderation_actions',
        "target_type IN ('review', 'complaint', 'evidence', 'response', "
        "'company', 'user', 'badge', 'representative')",
    )
    op.drop_index(op.f('ix_comments_review_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_complaint_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
