"""review problems checklist

Revision ID: 8fbd58b368e1
Revises: 497b93f73b9a
Create Date: 2026-07-23 18:31:08.823303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbd58b368e1'
down_revision: Union[str, Sequence[str], None] = '497b93f73b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_problems',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.CheckConstraint("problem IN ('unpaid_salary', 'delayed_salary', 'no_pension_contributions', 'unpaid_overtime', 'unpaid_holiday_work', 'no_contract', 'illegal_fines', 'no_vacation', 'no_sick_leave', 'unsafe_conditions', 'illegal_dismissal', 'no_final_settlement', 'forced_labor')", name=op.f('ck_review_problems_problem_valid')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_problems_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_problems')),
    sa.UniqueConstraint('review_id', 'problem', name=op.f('uq_review_problems_review_id'))
    )
    op.create_index(op.f('ix_review_problems_review_id'), 'review_problems', ['review_id'], unique=False)
    # Дерек-көшіру: ескі illegal_fines белгілері жаңа кестеге, содан кейін ғана баған өшеді
    op.execute(
        "INSERT INTO review_problems (review_id, problem) "
        "SELECT id, 'illegal_fines' FROM reviews WHERE illegal_fines = true"
    )
    op.drop_column('reviews', 'illegal_fines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('illegal_fines', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_review_problems_review_id'), table_name='review_problems')
    op.drop_table('review_problems')
    # ### end Alembic commands ###
